# Generated by Django 4.1.1 on 2022-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(default='avatar.png', upload_to='products'),
        ),
    ]
